url: http://www.ebpr.ch
title: EBPR
description: EBPR bietet umfassende Kommunikationslösungen für das Luxussegment.
author: EBPR
permalink: /:title
exclude:
- tasks
sass:
    sass_dir: _sass
    style: :compressed
defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
